# Jekyll / GitHub Pages — https://docs.github.com/en/pages
title: Архивирование в Linux
description: zip, tar, gzip, xz, zstd, pv и удобные алиасы в Bash
theme: jekyll-theme-cayman
markdown: kramdown

# Проектный сайт https://zenc0dr.github.io/c0dr/ — имя репозитория со слэшем:
baseurl: "/c0dr"

# Для корневого сайта https://zenc0dr.github.io/ переименуйте репо в zenc0dr.github.io и поставьте:
# baseurl: ""

url: "https://zenc0dr.github.io"
